version: "3"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    networks:
      - proxy-network

  acme-companion:
    image: nginxproxy/acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=dev@kruxlab.com
    networks:
      - proxy-network

  jokadetailing:
    build: ./jokadetailing
    environment:
      - VIRTUAL_HOST=jokadetailing.com,www.jokadetailing.com
      - LETSENCRYPT_HOST=jokadetailing.com,www.jokadetailing.com
    networks:
      - proxy-network

  kruxlab:
    build: ./kruxlab
    environment:
      - VIRTUAL_HOST=kruxlab.com,www.kruxlab.com
      - LETSENCRYPT_HOST=kruxlab.com,www.kruxlab.com
    networks:
      - proxy-network

  thomasjuranek:
    build: ./thomasjuranek
    environment:
      - VIRTUAL_HOST=thomasjuranek.com,www.thomasjuranek.com
      - LETSENCRYPT_HOST=thomasjuranek.com,www.thomasjuranek.com
    networks:
      - proxy-network

volumes:
  certs:
  vhost:
  html:
  acme:

networks:
  proxy-network:
    name: proxy-network
