name: Deploy Website

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy websites
        env:
          PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USER@$HOST << 'EOF'
            cd sites
            git pull
            
            # Update each website
            for website in websites/*/; do
              website_name=$(basename "$website")
              echo "Updating $website_name"
              docker-compose -f docker-compose.yml -f "$website/docker-compose.yml" down --rmi local
              docker-compose -f docker-compose.yml -f "$website/docker-compose.yml" up -d --build
            done
            
            # Prune Docker system
            docker system prune -af
          EOF

      - name: Cleanup
        if: always()
        run: rm -f private_key
